# Generated by Django 3.1.3 on 2020-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('link_hash', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Hash')),
                ('link', models.TextField(verbose_name='Link')),
            ],
        ),
    ]
