# Generated by Django 3.1.3 on 2020-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_linker_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='link',
            field=models.CharField(max_length=300, verbose_name='Link'),
        ),
    ]
